### ISSUE TITLE
Add MyFamily

### ISSUE THREAD

**Issue by pastly** [lukechilds/onionite#10]
Atlas will display a relay's family as a list of fingerprints that link to the relays' pages. I find this very useful.

**Comment by lukechilds** [comment]
Sure.

Out of interest, what did you find useful about the family information?

**Comment by pastly** [comment]
I can quickly move between all my nodes as I've setup MyFamily correctly. I also like to see if some other relay is just a single large one or part of a family of large ones by clicking through to its relatives.

I think this is an important feature, especially if you market onionite as an Atlas replacement :)

**Comment by lukechilds** [comment]
I see, yeah should be fairly trivial to implement. I think I'll have time to get it done over weekend.

Thanks for the suggestion, I'll keep you posted 👍

**Comment by lukechilds** [comment]
@pastly @scriptzteam Sorted.

Example: https://onionite.now.sh/node/5CECC5C30ACC4B3DE462792323967087CC53D947

Added it to the "Meta" section.
